### ISSUE TITLE
A way to exact match ?

### ISSUE THREAD

**Issue by visualight** [ajcastro/searchable#10]
I have successfully implemented your package and I am very happy with it but the search results are not strict enough. Is there a method to make an exact mactch of what we type in the search? Your package is intended to find trades. Suddenly if I currently type: "gardener", the search also sends me booksellers when no occurrence of this word exists in the text.

Tests carried out with several records and only one. 
Thank you

**Comment by ajcastro** [comment]
@visualight 
You can extend the class `AjCastro\Searchable\Search\SublimeSearch` a.k.a a fuzzy-search implementation.  

```php
namespace App;

use AjCastro\Searchable\Search\SublimeSearch;

class ExactSearch extends SublimeSearch 
{
    /**
     * {@inheritDoc}
     */
    protected function parseSearchStr($searchStr)
    {
        return $searchStr; // produces "where `column` like '{$searchStr}'" 
        // or
        return "%{$searchStr}%"; // produces "where `column` like '%{$searchStr}%'" 
    }
}
```

then use it in the model:

```php

namespace App;

class User extends Model 
{
    public function defaultSearchQuery() 
    {
        return new ExactSearch($this, $this->searchableColumns(), $this->sortByRelevance, 'where');
    }
}
```
You may also check the build query by dd-ing it:

```php

$query = User::search('John Doe');
dd($query->toSql());
```
which may output to 
```
select * from users where `column` like 'John Doe'
// or
select * from users where `column` like '%John Doe%'
```

**Comment by visualight** [comment]
AWESOME ! AjCastro\Searchable is now one of my favorite package.
Thanks dude !!
