### ISSUE TITLE
Not Full-Text queries

### ISSUE THREAD

**Issue by johnwc** [ajcastro/searchable#12]
To be clear, this is not Full-Text searching. This is [pattern matching](https://dev.mysql.com/doc/refman/8.0/en/pattern-matching.html), which causes a db to do a full scan on the table instead of using indexes. 

[Full-Text queries](https://dev.mysql.com/doc/refman/8.0/en/fulltext-search.html) use much different sql statements.

**Comment by ajcastro** [comment]
Thanks @johnwc for the correction! I updated the readme for that
