### ISSUE TITLE
Broken search string?

### ISSUE THREAD

**Issue by anthros-niccolo** [ajcastro/searchable#13]
I'm not sure how this was supposed to work, but if I search for `TEST`, MySQL query is `%T%E%S%T%`—which looks for those letters.

In `SublimeSearch::parseSearchStr`, I see:

```php
'%'.join('%', str_split($searchStr)).'%';
```

What's the purpose of this?

**Comment by ajcastro** [comment]
@anthros-niccolo that is fuzzy search... the class name should be changed to FuzzySearch

**Comment by anthros-niccolo** [comment]
Oh, I see.

I didn't realize was fuzzy search by default.

Cool! Thanks.
